language: php
php:
  - '5.6'
  - '7.0'
before_install:
  - pecl channel-update pecl.php.net
  - echo yes | pecl install memcache
  - composer install --dev
  - sudo service elasticsearch start
  - sleep 3
  
services:
  - elasticsearch
  
script: ./runtests.sh
